{
  version: '0.2',
  phases: {
    install: {
      commands: [
        'npm install',
      ]
    },
    build: {
      commands: [
        'npm run build',
        'npm run cdk synth UserService-LambdasStack -- -o dist --app "npx ts-node sample/index.ts"'
      ],
    },
  },
  artifacts: {
    'base-directory': 'dist',
    files: [
      'UserService-LambdasStack.template.json',
    ],
  },
}