{
  version: '0.2',
  phases: {
    install: {
      commands: [
        'cd sample',
        'npm install',
      ]
    },
    build: {
      commands: [
        'npm run build',
        'cdk synth UserService-LambdasStack -o dist'
      ],
    },
  },
  artifacts: {
    'base-directory': 'dist',
    files: [
      'UserService-LambdasStack.template.json',
    ],
  },
}