{
  version: '0.2',
  phases: {
    install: {
      commands: [
        'cd sample/lambda',
        'npm install',
      ],
    },
    build: {
      commands: 'npm run build',
    },
  },
  artifacts: {
    'base-directory': 'sample/lambda',
    files: [
      'userCreate.js',
      'userGet.js',
      'node_modules/**/*',
    ],
  },
}